[build]
  publish = "."

[functions]
  node_bundler = "zisi"

[functions."natal-chart"]
  node_bundler = "zisi"

[functions."human-design"]
  node_bundler = "zisi"

[functions."life-coach"]
  node_bundler = "zisi"

[functions."life-copilot"]
  node_bundler = "zisi"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
